<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedecinRepository extends EntityRepository
{
    public function findWithRegion($id){
        try {
            return $this->createQueryBuilder('m')
                ->select('m, v, d, r')
                ->join('m.ville', 'v')
                ->join('v.departement', 'd')
                ->join('d.region', 'r')
                ->where('m.id = :id')
                ->setParameter(':id', $id)
                ->getQuery()
                ->getSingleResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
    }

    public function findAllWithRegion(){
        return $this->createQueryBuilder('m')
            ->select('m, v, d, r')
            ->join('m.ville', 'v')
            ->join('v.departement', 'd')
            ->join('d.region', 'r')
            ->getQuery()
            ->getResult();
    }
}
